version: "3"
services:
  wiremock:
    image: "wiremock/wiremock:3.3.1"
    container_name: my_wiremock
    ports:
      - "8080:8080"
    volumes:
      - ./__files:/home/wiremock/__files
      - ./mappings:/home/wiremock/mappings
    entrypoint: ["/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose", "--enable-browser-proxying"]
